
# html lang
language: cn

# header
site_brand_name: loVault

logo_image:
  enable: true
  image_path: /logo.png # path to your logo image (light mode)
  dark_path: /logo-dark.png # path to your dark mode logo image

# font toggle button (serif / sans-serif)
font_toggle:
  enable: true
  sans_label: 'Inter + Noto Sans SC'
  serif_label: 'Lora + Source Han Serif'

menu:
  主页: /
  归档: /archives/
  画廊: /categories/gallery/

# stylesheets loaded in the <head>
stylesheets:
- /css/style.css

# scripts loaded in the end of the body
scripts:
- /js/menu.js

# favicon
favicon: /favicon.ico

date_format: MMM D, YYYY

# profile
profile:
  title: 你好，我是 Julius。
  body: 欢迎你来到这里。
  image: /profile_cover.png

  links:
    给我发邮件: mailto:suhzin@outlook.com
    我的微信: copy:Ridflinb7
    CC98 主帖: https://www.cc98.org/topic/6410055

# footer
footer:
  copyright_info:
    enable: true
    author: © Julius Long

  powered_by: # Powered by Hexo & Frame
    enable: true


  other_info:
    enable: true
    content: "<i>I'm Tantalus, can't help but reach out and touch...</i>"

# color mode: default / classic / dark / auto (auto supports light/dark toggle)
color_mode: auto

# theme toggle button
theme_toggle:
  enable: true

# mathjax setting
# note: need to install the hexo plugin for math: https://github.com/hexojs/hexo-math
mathjax_enable: true

# comments: support disqus and valine
valine: # valine setup guide: https://valine.js.org/quickstart.html
  enable: false
  appId: # Your valine app Id
  appKey: # Your valine app Key
  lang: 'en'
  placeholder: 'Say something'
  avatar: 'mp'
  meta: ['nick', 'mail']

disqus: # disqus setup guide: https://help.disqus.com/en/articles/1717056-publisher-quick-start-guide
  enable: false
  disqus_url: # your diqsuq url or shortname
  language: 'en'

# local search
local_search:
  enable: true
  path: search.json
  place_holder: 支持文件名称与内容查找 :)
  trigger: auto # auto: trigger search whenever input changes
  top_n_per_article: -1 # show top n results per article, show all results by setting to -1
  unescape: false # unescape html strings to the readable one
  preload: false # reload the search data when the page loads, this will accelerate the search process
